Friend Module Columns
    Friend Const COLUMN_FACTION_ID = "faction_id"
    Friend Const COLUMN_FACTION_NAME = "faction_name"
    Friend Const COLUMN_PROFILE_ID = "profile_id"
    Friend Const COLUMN_PROFILE_NAME = "profile_name"
    Friend Const COLUMN_UNIT_ID = "unit_id"
    Friend Const COLUMN_UNIT_NAME = "unit_name"
    Friend Const COLUMN_BUILDING_ID = "building_id"
    Friend Const COLUMN_BUILDING_NAME = "building_name"
    Friend Const COLUMN_HOUSING_ID = "housing_id"
    Friend Const COLUMN_COUNTER_TYPE_ID = "counter_type_id"
    Friend Const COLUMN_COUNTER_TYPE_NAME = "counter_type_name"
    Friend Const COLUMN_UNIT_TYPE_ID = "unit_type_id"
    Friend Const COLUMN_UNIT_TYPE_NAME = "unit_type_name"
End Module
