Friend Module Columns
    Friend Const COLUMN_UNIVERSE_ID = "universe_id"
    Friend Const COLUMN_UNIVERSE_NAME = "universe_name"
    Friend Const COLUMN_FACTION_ID = "faction_id"
    Friend Const COLUMN_FACTION_NAME = "faction_name"
    Friend Const COLUMN_STAR_ID = "star_id"
    Friend Const COLUMN_STAR_NAME = "star_name"
    Friend Const COLUMN_STAR_X = "star_x"
    Friend Const COLUMN_STAR_Y = "star_y"
    Friend Const COLUMN_STAR_Z = "star_z"
    Friend Const COLUMN_PARTY_ID = "party_id"
    Friend Const COLUMN_PLAYER_PARTY_ID = "player_party_id"
    Friend Const COLUMN_SHIP_ID = "ship_id"
    Friend Const COLUMN_SHIP_NAME = "ship_name"
    Friend Const COLUMN_SHIP_X = "ship_x"
    Friend Const COLUMN_SHIP_Y = "ship_y"
    Friend Const COLUMN_SHIP_Z = "ship_z"
    Friend Const COLUMN_DISTANCE = "distance"
End Module
