Friend Module Tables
    Friend Const TABLE_FACTIONS = "factions"
    Friend Const TABLE_PROFILES = "profiles"
    Friend Const TABLE_UNITS = "units"
    Friend Const TABLE_BUILDINGS = "buildings"
    Friend Const TABLE_HOUSINGS = "housings"
    Friend Const VIEW_FACTION_AVAILABLE_HOUSINGS = "faction_available_housings"
    Friend Const VIEW_FACTION_UNHOUSED_UNITS = "faction_unhoused_units"
    Friend Const TABLE_COUNTER_TYPES = "counter_types"
    Friend Const TABLE_UNIT_TYPES = "unit_types"
    Friend Const TABLE_UNIT_TYPE_COUNTERS = "unit_type_counters"
    Friend Const VIEW_UNIT_TYPE_AVAILABLE_COUNTER_TYPES = "unit_type_available_counter_types"
    Friend Const TABLE_UNIT_COUNTERS = "unit_counters"
    Friend Const VIEW_UNIT_COUNTER_DETAILS = "unit_counter_details"
End Module
